### ISSUE TITLE
Timetable is not correctly filtered

### ISSUE THREAD

**Issue by egeldenhuys** [egeldenhuys/emptiness#1]
Getting an almost full timetable when using `t = 23:00`

**Comment by egeldenhuys** [comment]
Problem 1:

We are modifying the `timetable` argument passed by reference from the `getFilteredTimetable` function. This was not the expected behavior.
This caused the venue list generated after the filter process to be incorrect as the timetable has been filtered.

Problem 2:
```
copy.copy(x)
Return a shallow copy of x.

copy.deepcopy(x)
Return a deep copy of x.
```

**Comment by CDuPlooy** [comment]
I thought of a few possible issues for problem 1:
* exTime code is misbehaving.
* [range](http://stackoverflow.com/questions/4504662/why-does-rangestart-end-not-include-end) does not work as we expect it to.
* The obvious 👍 comparisons might be slightly misguided.

**Comment by egeldenhuys** [comment]
With `t = 23:00`
the else block is never executed, as expected

```python
if not (timeMins in range(start, end)):
	newTimetable.remove(entry)
else:
	print(str(timeMins) + ' is in range of ' + '[' + str(start) + ', ' + str(end) + ']')
```

**Comment by egeldenhuys** [comment]
Fixed by reworking the logic to `append` instead of `remove`

**Comment by CDuPlooy** [comment]
This seems obvious in retrospect xD
