### ISSUE TITLE
Emptiness as a Service

### ISSUE THREAD

**Issue by egeldenhuys** [egeldenhuys/emptiness#2]
It would be nice to access a URL and have it tell me which venues are currently open, and will be open in the next block. This way when a user checks the page at 14:13 they can easily see if a venue that appears to be open will continue to stay open.

Example output if the current time is 14:00 :
```
Emptiness v1.0.0 @ 14:00

Empty Venues
------------
13:30 -> 14:30
HB 4-3
IT 1-1
etc...

14:30 -> 15:30
etc...
```

**Comment by egeldenhuys** [comment]
See branch [server](https://github.com/egeldenhuys/emptiness/tree/server)

**Comment by egeldenhuys** [comment]
Current output from http://emptiness.mooo.com/

![screenshot from 2017-02-11 21-32-34](https://cloud.githubusercontent.com/assets/5778739/22856800/a63333be-f0a1-11e6-8deb-adca77ee665f.png)

**Comment by devosray** [comment]
This is awesome. Are you really hosting this on a RPi3?

**Comment by egeldenhuys** [comment]
Yes, hosting from my RPi3 :smiley:

**Comment by CDuPlooy** [comment]
I think from a security point of view the applet should not be outputting what kind of server it's running on.

**Comment by egeldenhuys** [comment]
Made some security improvements in 1397064, such as escaping data read from log files and no longer displaying server information.
